# Generated by Django 4.2.2 on 2023-10-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('info', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('social_github', models.CharField(blank=True, max_length=300, null=True)),
                ('social_youtube', models.CharField(blank=True, max_length=300, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('social_telegram', models.CharField(blank=True, max_length=300, null=True)),
                ('personal_website', models.CharField(blank=True, max_length=300, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=300, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('social_leetcode', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='profiles/default_profile.webp', upload_to='profiles')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profil')),
            ],
        ),
    ]
